### ISSUE TITLE
Please make new LuaRock release

### ISSUE THREAD

**Issue by rrthomas** [kikito/ansicolors.lua#4]
I agree completely that LuaRocks releases should be automated; mine are! See for example luaposix/luaposix's Makefile.am, and note that because you use LuaRocks's built-in build system you don't need the "foo-release" branch bit, so the code will be that bit simpler. Do ask if I can help.

**Comment by kikito** [comment]
> See for example luaposix/luaposix's Makefile.am

Woah, that looks like a lot of work. There's something about Makefile's syntax that doesn't click with my brain. I have done other build systems (rake, grunt), but I dislike make for some reason.

> note that because you use LuaRocks's built-in build system you don't need the "foo-release" branch bit, 

I don't know what the terms "LuaRocks's built-in build system" and "the 'foo-release' branch bit" mean. So I could not understand that last part :/ . It seems to imply that I'm doing something that I don't need to keep doing. What is that?

In any case, I have done it "the manual way" - updated the rockspec file manually and posted a message to the mailing list. Hopefully they will act on it soon.

**Comment by rrthomas** [comment]
The Makefile-ness isn't important: look at the shell code under the "release" target near the bottom.

LuaRocks can control Makefile-based and GNU autotools-based build systems, and also CMake. You opt to use its built-in build system. This makes things simpler, and means that you can get away without needing to do something an autotools user needs (specifically, having a git branch with generated sources checked in). So you don't need to change anything.

The main parts of my system you could use are mkrockspecs.lua and rockspecs.lua, which generate the rockspec for a new version (though luarocks's new_version command might suffice for you), and woger to send the rockspec to the LuaRocks mailing list, though again you could just use a simple "mail" command.

**Comment by kikito** [comment]
Thanks for the pointers, I will check all those out.

I think it's a good habit to tag every library release on the source code, and it's also very easily done.

I hope that luarocks improves somehow in the future (or at least that it doesn't require posting to a mailing list).

**Comment by rrthomas** [comment]
Note that LuaRocks not being automatic is only a problem for developers because it means you don't know how long it will take for a release to appear on luarocks.org. The fact that you have to send mail to a mailing list doesn't matter: you can do that with a program. In fact, it's a good choice of implementation method, because if luarocks.org is automated, there will be no need to change the method of sending a rockspec to a mailing list; instead, it can simply be handled by a computer instead of a human.

**Comment by kikito** [comment]
I created and posted the rock but then forgot to close down this issue. Closing now.
