### ISSUE TITLE
[this issue its not for this, but i need help] related problem

### ISSUE THREAD

**Issue by alexzanderr** [kikito/ansicolors.lua#9]
hey, very nice lua file.
im trying to use this in neovim lua configuration.

but when trying to print this:
```lua
local colored = require("ansi-colors")


function copy_current_line_to_clipboard()
	vim.cmd("execute 'normal \"+yy'")
	print(colored("%{red}line copied to clipboard%{reset}"))
end

nnoremap("<C-c>", "<cmd> lua copy_current_line_to_clipboard()<CR>")
inoremap("<C-c>", "<C-o><cmd> lua copy_current_line_to_clipboard()<CR>")
```

i get this:
![image](https://user-images.githubusercontent.com/54772464/134029418-6fd6d4ce-280e-45e2-91d8-78b14a13cd23.png)

i've tested the file in my terminal:
![image](https://user-images.githubusercontent.com/54772464/134029488-1d245160-c11a-4d84-a88c-8b4876872644.png)

with this:
```lua


local colored = require("ansi-colors")
print(colored("%{red}line copied to clipboard%{reset}"))
```

so the plugin works.

apparently, vim cannot display ansi codes.

how do i make neovim display ansi codes in command-line area?

**Comment by Tieske** [comment]
That question should be better posted in the neovim community.

**Comment by alexzanderr** [comment]
yeah. later i found out that its not related to this plugin.

**Comment by alexzanderr** [comment]
do you have any ideas?

**Comment by Tieske** [comment]
Nope, don't know neovim. Can we close this please?

**Comment by alexzanderr** [comment]
sure
